version: 2

jobs:
    build:
      machine: true
      steps:
        - checkout
        - run: wget -qO- get.nextflow.io | bash ; chmod 755 nextflow ; sudo ln -s ~/project/nextflow /usr/local/bin/ ; sudo apt-get install graphviz
        - run: cd ~ && git clone --depth=1 https://github.com/IARCbioinfo/data_test.git
        - run: echo " docker.runOptions = '-u $(id -u):$(id -g)' " > ~/.nextflow/config
        - run: cd ~/project/ ; docker build -t iarcbioinfo/vt-nf .
        - run: nextflow run ~/project/vt.nf -with-docker iarcbioinfo/vt-nf --help
        - run: nextflow run ~/project/vt.nf -with-docker iarcbioinfo/vt-nf --vcf_folder ~/data_test/VCF --ref ~/data_test/REF/17.fasta
        - run: nextflow run ~/project/vt.nf -with-docker iarcbioinfo/vt-nf --vcf_folder ~/data_test/VCF --ref ~/data_test/REF/17.fasta
        - run: nextflow run ~/project/vt.nf -with-docker iarcbioinfo/vt-nf --vcf_folder ~/data_test/VCF --ref ~/data_test/REF/17.fasta
        - run: cd ; mv ~/nf-pipeline_info/vt_dag.html ~/project/
        - deploy:
            branch: [dev, master]
            command: chmod +x deploy.sh && ./deploy.sh
